#!/bin/sh

module="nfstat"
device="nf-stat"
mode="664"

if grep '^staff:' /etc/group > /dev/null; then
    group="staff"
else
    group="wheel"
fi

/sbin/insmod ./$module.ko || exit 1

major=$(awk "\$2==\"$device\" {print \$1}" /proc/devices)
rm -f /dev/${device}
mknod /dev/${device} c $major 0
chgrp $group /dev/${device}
chmod $mode /dev/${device}

